import type { ProviderBusiness, SearchProvider, SearchProviderParams } from "./types";

/**
 * Provider de desenvolvimento — substitui uma fonte externa real (Google
 * Places, etc.) enquanto nenhuma credencial estiver configurada (ver
 * provider.ts). Todas as empresas abaixo são fictícias. Os dados variam de
 * propósito entre completos e incompletos (telefone/site/Instagram ausentes)
 * para exercitar o enriquecimento e a pontuação de ICP com dados reais de
 * qualidade desigual, como aconteceria com uma fonte real.
 */

type MockBusiness = ProviderBusiness;

function biz(partial: Partial<MockBusiness> & Pick<MockBusiness, "externalId" | "company" | "segment" | "city" | "state">): MockBusiness {
  return {
    type: null,
    address: null,
    phone: null,
    website: null,
    instagram: null,
    linkedin: null,
    email: null,
    cnpj: null,
    sourceUrl: null,
    rating: null,
    userRatingCount: null,
    employees: null,
    estimatedRevenue: null,
    adSpend: null,
    potentialValue: null,
    commercialMaturity: null,
    marketingNeed: null,
    technologyNeed: null,
    recurrencePotential: null,
    technologyStack: null,
    ...partial,
  };
}

const MOCK_BUSINESSES: MockBusiness[] = [
  biz({
    externalId: "mock-001",
    company: "Nuvem Moda E-commerce",
    segment: "E-commerce de moda",
    city: "São Paulo",
    state: "SP",
    phone: "11987654321",
    website: "nuvemmoda.com.br",
    instagram: "@nuvemmoda",
    email: "contato@nuvemmoda.com.br",
    cnpj: "12345678000101",
    employees: 22,
    estimatedRevenue: 420000,
    adSpend: 15000,
    potentialValue: 6500,
    commercialMaturity: 70,
    marketingNeed: 80,
    technologyNeed: 55,
    recurrencePotential: 75,
    technologyStack: ["Shopify", "RD Station"],
  }),
  biz({
    externalId: "mock-002",
    company: "Casa Bella Decor E-commerce",
    segment: "E-commerce de decoração",
    city: "São Paulo",
    state: "SP",
    phone: "11976543210",
    website: "casabelladecor.com.br",
    instagram: "@casabelladecor",
    cnpj: "12345678000202",
    employees: 12,
    estimatedRevenue: 180000,
    adSpend: 4000,
    potentialValue: 3200,
    commercialMaturity: 55,
    marketingNeed: 65,
    technologyNeed: 40,
    recurrencePotential: 60,
  }),
  biz({
    externalId: "mock-003",
    company: "TechFit Suplementos",
    segment: "E-commerce",
    city: "São Paulo",
    state: "SP",
    website: "techfitsuplementos.com.br",
    instagram: "@techfitsuplementos",
    email: "vendas@techfitsuplementos.com.br",
    employees: 8,
    estimatedRevenue: 95000,
    adSpend: 1800,
    potentialValue: 1900,
    commercialMaturity: 40,
    marketingNeed: 55,
    technologyNeed: 45,
    recurrencePotential: 50,
  }),
  biz({
    externalId: "mock-004",
    company: "Petiscos & Cia E-commerce Pet",
    segment: "E-commerce",
    city: "São Paulo",
    state: "SP",
    phone: "11998877665",
    employees: 5,
    estimatedRevenue: 40000,
    potentialValue: 900,
    commercialMaturity: 20,
    marketingNeed: 30,
    technologyNeed: 25,
    recurrencePotential: 35,
  }),
  biz({
    externalId: "mock-005",
    company: "Luxe Bijoux E-commerce",
    segment: "E-commerce de joias",
    city: "São Paulo",
    state: "SP",
    phone: "11991122334",
    website: "luxebijoux.com.br",
    instagram: "@luxebijoux",
    linkedin: "linkedin.com/company/luxebijoux",
    email: "contato@luxebijoux.com.br",
    cnpj: "12345678000303",
    employees: 30,
    estimatedRevenue: 610000,
    adSpend: 22000,
    potentialValue: 9800,
    commercialMaturity: 85,
    marketingNeed: 70,
    technologyNeed: 60,
    recurrencePotential: 88,
    technologyStack: ["VTEX", "Meta Ads", "Klaviyo"],
  }),
  biz({
    externalId: "mock-006",
    company: "Studio Fit Academia",
    segment: "Academia",
    city: "São Paulo",
    state: "SP",
    phone: "11933445566",
    instagram: "@studiofitacademia",
    employees: 15,
    estimatedRevenue: 130000,
    adSpend: 2500,
    potentialValue: 2100,
    commercialMaturity: 45,
    marketingNeed: 60,
    technologyNeed: 50,
    recurrencePotential: 90,
  }),
  biz({
    externalId: "mock-007",
    company: "Sorriso Odonto Clínica",
    segment: "Clínica odontológica",
    city: "Campinas",
    state: "SP",
    phone: "19987001122",
    website: "sorrisoodonto.com.br",
    instagram: "@sorrisoodonto",
    cnpj: "12345678000404",
    employees: 18,
    estimatedRevenue: 250000,
    adSpend: 6000,
    potentialValue: 4200,
    commercialMaturity: 60,
    marketingNeed: 70,
    technologyNeed: 45,
    recurrencePotential: 80,
  }),
  biz({
    externalId: "mock-008",
    company: "Advocacia Martins & Souza",
    segment: "Escritório de advocacia",
    city: "Campinas",
    state: "SP",
    phone: "19933221100",
    email: "contato@martinssouza.adv.br",
    employees: 10,
    estimatedRevenue: 200000,
    potentialValue: 3500,
    commercialMaturity: 35,
    marketingNeed: 40,
    technologyNeed: 30,
    recurrencePotential: 55,
  }),
  biz({
    externalId: "mock-009",
    company: "Auto Peças Campinas Center",
    segment: "Auto peças",
    city: "Campinas",
    state: "SP",
    phone: "19981234567",
    employees: 25,
    estimatedRevenue: 380000,
    potentialValue: 5000,
    commercialMaturity: 30,
    marketingNeed: 45,
    technologyNeed: 35,
    recurrencePotential: 40,
  }),
  biz({
    externalId: "mock-010",
    company: "Bella Beauty Salão",
    segment: "Salão de beleza",
    city: "Rio de Janeiro",
    state: "RJ",
    phone: "21987654321",
    instagram: "@bellabeautyrj",
    employees: 9,
    estimatedRevenue: 85000,
    adSpend: 900,
    potentialValue: 1200,
    commercialMaturity: 25,
    marketingNeed: 50,
    technologyNeed: 35,
    recurrencePotential: 65,
  }),
  biz({
    externalId: "mock-011",
    company: "Rio Fashion E-commerce",
    segment: "E-commerce de moda",
    city: "Rio de Janeiro",
    state: "RJ",
    phone: "21998765432",
    website: "riofashion.com.br",
    instagram: "@riofashionrj",
    linkedin: "linkedin.com/company/riofashion",
    email: "sac@riofashion.com.br",
    cnpj: "12345678000505",
    employees: 28,
    estimatedRevenue: 540000,
    adSpend: 18000,
    potentialValue: 7200,
    commercialMaturity: 78,
    marketingNeed: 75,
    technologyNeed: 58,
    recurrencePotential: 82,
    technologyStack: ["Nuvemshop", "RD Station", "Google Ads"],
  }),
  biz({
    externalId: "mock-012",
    company: "Consultório Dr. Ricardo Alves",
    segment: "Consultório médico",
    city: "Rio de Janeiro",
    state: "RJ",
    phone: "21991223344",
    employees: 4,
    estimatedRevenue: 60000,
    potentialValue: 1500,
    commercialMaturity: 20,
    marketingNeed: 35,
    technologyNeed: 20,
    recurrencePotential: 45,
  }),
  biz({
    externalId: "mock-013",
    company: "Imobiliária Costa Verde",
    segment: "Imobiliária",
    city: "Belo Horizonte",
    state: "MG",
    phone: "31987001234",
    website: "costaverdeimoveis.com.br",
    instagram: "@costaverdeimoveis",
    employees: 20,
    estimatedRevenue: 310000,
    adSpend: 8000,
    potentialValue: 4800,
    commercialMaturity: 55,
    marketingNeed: 60,
    technologyNeed: 40,
    recurrencePotential: 50,
  }),
  biz({
    externalId: "mock-014",
    company: "Padaria Pão Dourado",
    segment: "Padaria",
    city: "Belo Horizonte",
    state: "MG",
    phone: "31991112233",
    employees: 12,
    estimatedRevenue: 70000,
    potentialValue: 800,
    commercialMaturity: 15,
    marketingNeed: 25,
    technologyNeed: 15,
    recurrencePotential: 60,
  }),
  biz({
    externalId: "mock-015",
    company: "MG Tech Distribuidora",
    segment: "Distribuidora de tecnologia",
    city: "Belo Horizonte",
    state: "MG",
    phone: "31988997766",
    website: "mgtechdistribuidora.com.br",
    linkedin: "linkedin.com/company/mgtech",
    email: "comercial@mgtechdistribuidora.com.br",
    cnpj: "12345678000606",
    employees: 45,
    estimatedRevenue: 890000,
    adSpend: 12000,
    potentialValue: 11000,
    commercialMaturity: 82,
    marketingNeed: 50,
    technologyNeed: 70,
    recurrencePotential: 78,
    technologyStack: ["SAP", "Salesforce"],
  }),
  biz({
    externalId: "mock-016",
    company: "Curitiba SaaS Soluções B2B",
    segment: "SaaS B2B",
    city: "Curitiba",
    state: "PR",
    phone: "41987654321",
    website: "curitibasaas.com.br",
    instagram: "@curitibasaas",
    linkedin: "linkedin.com/company/curitibasaas",
    email: "hello@curitibasaas.com.br",
    cnpj: "12345678000707",
    employees: 38,
    estimatedRevenue: 720000,
    adSpend: 25000,
    potentialValue: 15000,
    commercialMaturity: 90,
    marketingNeed: 65,
    technologyNeed: 85,
    recurrencePotential: 95,
    technologyStack: ["HubSpot", "AWS", "Intercom"],
  }),
  biz({
    externalId: "mock-017",
    company: "Barbearia Vintage Curitiba",
    segment: "Barbearia",
    city: "Curitiba",
    state: "PR",
    instagram: "@vintagebarbearia",
    employees: 3,
    estimatedRevenue: 35000,
    potentialValue: 600,
    commercialMaturity: 15,
    marketingNeed: 40,
    technologyNeed: 20,
    recurrencePotential: 55,
  }),
  biz({
    externalId: "mock-018",
    company: "Estúdio Fotografia Luz & Cia",
    segment: "Fotografia",
    city: "Curitiba",
    state: "PR",
    phone: "41999887766",
    instagram: "@luzecia.foto",
    employees: 4,
    estimatedRevenue: 50000,
    adSpend: 500,
    potentialValue: 1000,
    commercialMaturity: 25,
    marketingNeed: 45,
    technologyNeed: 25,
    recurrencePotential: 40,
  }),
  biz({
    externalId: "mock-019",
    company: "Porto Alegre Contabilidade Digital",
    segment: "Contabilidade",
    city: "Porto Alegre",
    state: "RS",
    phone: "51987001122",
    website: "poacontabildigital.com.br",
    email: "atendimento@poacontabildigital.com.br",
    employees: 16,
    estimatedRevenue: 210000,
    adSpend: 3000,
    potentialValue: 3800,
    commercialMaturity: 50,
    marketingNeed: 55,
    technologyNeed: 60,
    recurrencePotential: 85,
  }),
  biz({
    externalId: "mock-020",
    company: "Sul Móveis Planejados",
    segment: "Loja de móveis",
    city: "Porto Alegre",
    state: "RS",
    phone: "51991223344",
    website: "sulmoveisplanejados.com.br",
    instagram: "@sulmoveisrs",
    cnpj: "12345678000808",
    employees: 22,
    estimatedRevenue: 340000,
    adSpend: 7000,
    potentialValue: 5200,
    commercialMaturity: 58,
    marketingNeed: 55,
    technologyNeed: 40,
    recurrencePotential: 45,
  }),
  biz({
    externalId: "mock-021",
    company: "Bahia Turismo Receptivo",
    segment: "Turismo",
    city: "Salvador",
    state: "BA",
    phone: "71987654321",
    instagram: "@bahiaturismo",
    employees: 7,
    estimatedRevenue: 120000,
    adSpend: 2000,
    potentialValue: 1800,
    commercialMaturity: 40,
    marketingNeed: 60,
    technologyNeed: 35,
    recurrencePotential: 50,
  }),
  biz({
    externalId: "mock-022",
    company: "Salvador Eventos & Cerimonial",
    segment: "Eventos",
    city: "Salvador",
    state: "BA",
    employees: 6,
    estimatedRevenue: 90000,
    potentialValue: 1600,
    commercialMaturity: 30,
    marketingNeed: 45,
    technologyNeed: 25,
    recurrencePotential: 35,
  }),
  biz({
    externalId: "mock-023",
    company: "Recife Ótica Visão Clara",
    segment: "Ótica",
    city: "Recife",
    state: "PE",
    phone: "81987001122",
    website: "visaoclararecife.com.br",
    employees: 11,
    estimatedRevenue: 160000,
    adSpend: 1500,
    potentialValue: 2400,
    commercialMaturity: 35,
    marketingNeed: 40,
    technologyNeed: 30,
    recurrencePotential: 55,
  }),
  biz({
    externalId: "mock-024",
    company: "Nordeste Farma Distribuidora",
    segment: "Farmácia",
    city: "Recife",
    state: "PE",
    phone: "81991122334",
    website: "nordestefarma.com.br",
    linkedin: "linkedin.com/company/nordestefarma",
    cnpj: "12345678000909",
    employees: 33,
    estimatedRevenue: 460000,
    adSpend: 9000,
    potentialValue: 6000,
    commercialMaturity: 62,
    marketingNeed: 50,
    technologyNeed: 55,
    recurrencePotential: 60,
  }),
  biz({
    externalId: "mock-025",
    company: "Fortaleza Petshop Amigo Fiel",
    segment: "Petshop",
    city: "Fortaleza",
    state: "CE",
    phone: "85987654321",
    instagram: "@amigofielfortaleza",
    employees: 8,
    estimatedRevenue: 75000,
    adSpend: 1200,
    potentialValue: 1100,
    commercialMaturity: 25,
    marketingNeed: 40,
    technologyNeed: 25,
    recurrencePotential: 70,
  }),
  biz({
    externalId: "mock-026",
    company: "Ceará Têxtil Indústria",
    segment: "Indústria têxtil",
    city: "Fortaleza",
    state: "CE",
    phone: "85991234567",
    website: "cearatextil.com.br",
    employees: 60,
    estimatedRevenue: 1200000,
    adSpend: 5000,
    potentialValue: 18000,
    commercialMaturity: 70,
    marketingNeed: 30,
    technologyNeed: 65,
    recurrencePotential: 50,
  }),
  biz({
    externalId: "mock-027",
    company: "Brasília Arquitetura & Design",
    segment: "Arquitetura",
    city: "Brasília",
    state: "DF",
    phone: "61987001122",
    instagram: "@bsbarquitetura",
    linkedin: "linkedin.com/company/bsbarquitetura",
    employees: 14,
    estimatedRevenue: 230000,
    adSpend: 3500,
    potentialValue: 4000,
    commercialMaturity: 55,
    marketingNeed: 55,
    technologyNeed: 40,
    recurrencePotential: 50,
  }),
  biz({
    externalId: "mock-028",
    company: "DF Construções Civis",
    segment: "Construção civil",
    city: "Brasília",
    state: "DF",
    phone: "61991122334",
    employees: 40,
    estimatedRevenue: 900000,
    potentialValue: 20000,
    commercialMaturity: 45,
    marketingNeed: 35,
    technologyNeed: 30,
    recurrencePotential: 30,
  }),
  biz({
    externalId: "mock-029",
    company: "Goiânia Agência de Marketing Digital",
    segment: "Agência de marketing",
    city: "Goiânia",
    state: "GO",
    phone: "62987654321",
    website: "goianiamkt.com.br",
    instagram: "@goianiamkt",
    linkedin: "linkedin.com/company/goianiamkt",
    email: "novosnegocios@goianiamkt.com.br",
    cnpj: "12345678001010",
    employees: 19,
    estimatedRevenue: 260000,
    adSpend: 4000,
    potentialValue: 3600,
    commercialMaturity: 65,
    marketingNeed: 45,
    technologyNeed: 60,
    recurrencePotential: 70,
    technologyStack: ["RD Station", "Meta Ads"],
  }),
  biz({
    externalId: "mock-030",
    company: "Ilha Verde Turismo Floripa",
    segment: "Turismo",
    city: "Florianópolis",
    state: "SC",
    phone: "48987001122",
    instagram: "@ilhaverdefloripa",
    employees: 9,
    estimatedRevenue: 140000,
    adSpend: 2800,
    potentialValue: 2200,
    commercialMaturity: 45,
    marketingNeed: 60,
    technologyNeed: 40,
    recurrencePotential: 55,
  }),
  biz({
    externalId: "mock-031",
    company: "Floripa Joalheria Fine",
    segment: "E-commerce de joias",
    city: "Florianópolis",
    state: "SC",
    website: "floripajoalheria.com.br",
    instagram: "@floripajoalheria",
    email: "contato@floripajoalheria.com.br",
    employees: 6,
    estimatedRevenue: 110000,
    adSpend: 2200,
    potentialValue: 2800,
    commercialMaturity: 40,
    marketingNeed: 55,
    technologyNeed: 35,
    recurrencePotential: 60,
  }),
  biz({
    externalId: "mock-032",
    company: "Amazônia Escola de Idiomas",
    segment: "Escola de idiomas",
    city: "Manaus",
    state: "AM",
    phone: "92987654321",
    instagram: "@amazoniaidiomas",
    employees: 13,
    estimatedRevenue: 95000,
    adSpend: 1000,
    potentialValue: 1400,
    commercialMaturity: 30,
    marketingNeed: 50,
    technologyNeed: 35,
    recurrencePotential: 88,
  }),
];

function matchesText(value: string | null, query: string): boolean {
  if (!value) return false;
  return value.toLowerCase().includes(query.toLowerCase());
}

async function searchBusinesses(params: SearchProviderParams): Promise<ProviderBusiness[]> {
  const { segment, city, state, keyword, quantity } = params;

  const filtered = MOCK_BUSINESSES.filter((business) => {
    if (segment && !matchesText(business.segment, segment)) return false;
    if (city && !matchesText(business.city, city)) return false;
    if (state && business.state?.toLowerCase() !== state.toLowerCase()) return false;
    if (keyword) {
      const haystack = `${business.company} ${business.segment ?? ""}`.toLowerCase();
      if (!haystack.includes(keyword.toLowerCase())) return false;
    }
    return true;
  });

  return filtered.slice(0, quantity);
}

async function getBusinessDetails(externalId: string): Promise<ProviderBusiness | null> {
  return MOCK_BUSINESSES.find((business) => business.externalId === externalId) ?? null;
}

export const mockSearchProvider: SearchProvider = {
  id: "mock",
  label: "Provider Mock (desenvolvimento)",
  searchBusinesses,
  getBusinessDetails,
};
